"""added acronym field to items

Revision ID: 0ae54d8985be
Revises: 3910ead3fabf
Create Date: 2019-09-18 13:42:30.386328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae54d8985be'
down_revision = '3910ead3fabf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('acronym', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'acronym')
    # ### end Alembic commands ###
