"""added nutritionURL to items model

Revision ID: 5827e498f82b
Revises: be4bc9997521
Create Date: 2019-09-25 13:35:53.379685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5827e498f82b'
down_revision = 'be4bc9997521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('nutritionURL', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'nutritionURL')
    # ### end Alembic commands ###
