"""added fields to listing

Revision ID: 6aff39b65db9
Revises: 884aa0e5af2d
Create Date: 2019-09-19 14:45:51.661683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aff39b65db9'
down_revision = '884aa0e5af2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('description', sa.String(length=2048), nullable=True))
    op.add_column('listing', sa.Column('weekdayHrs', sa.String(length=50), nullable=True))
    op.add_column('listing', sa.Column('weekendHrs', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'weekendHrs')
    op.drop_column('listing', 'weekdayHrs')
    op.drop_column('listing', 'description')
    # ### end Alembic commands ###
