"""item preferences

Revision ID: 884aa0e5af2d
Revises: 0ae54d8985be
Create Date: 2019-09-18 14:55:57.626342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884aa0e5af2d'
down_revision = '0ae54d8985be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_user_pref',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('itemPref', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_user_pref')
    # ### end Alembic commands ###
