"""added percntLikes field to listing model

Revision ID: 8ec6c5839c3d
Revises: 6aff39b65db9
Create Date: 2019-09-23 14:42:59.542294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec6c5839c3d'
down_revision = '6aff39b65db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('percentLikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'percentLikes')
    # ### end Alembic commands ###
