"""added imageurl to listing and item

Revision ID: 91e8dd5d9d62
Revises: 297f27043180
Create Date: 2019-09-11 21:09:52.584563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e8dd5d9d62'
down_revision = '297f27043180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('imageurl', sa.String(length=2048), nullable=True))
    op.add_column('listing', sa.Column('imageurl', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'imageurl')
    op.drop_column('item', 'imageurl')
    # ### end Alembic commands ###
