"""added restaurant field

Revision ID: be4bc9997521
Revises: cc2e10f5567a
Create Date: 2019-09-25 13:22:02.220692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4bc9997521'
down_revision = 'cc2e10f5567a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('restaurant', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'restaurant')
    # ### end Alembic commands ###
