"""upvote downvote added to item

Revision ID: d583f5dad208
Revises: 91e8dd5d9d62
Create Date: 2019-09-12 22:37:49.519054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd583f5dad208'
down_revision = '91e8dd5d9d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('votedown', sa.Boolean(), nullable=True))
    op.add_column('item', sa.Column('voteup', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'voteup')
    op.drop_column('item', 'votedown')
    # ### end Alembic commands ###
